# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 925fdc197979f4c440235b2d2503da23260073706cc431f498b9e07e79055670259cee32011715928bf8e1db60c0572b744f9b40e9b2477750a44a6a218aad1a

test:
  secret_key_base: b9a0fd5e781528d01bf1d49cbe0e775ef5df14d296905e2d5a54049b495090be967487623318e337b47f354b170a7394dc6d208bd399cf90693624ccba171f5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
